version: v1.0
name: Deploy Limn
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: aws-limn
      jobs:
        - name: Copy to S3
          commands:
            - checkout
            - cache restore website-build
            - aws s3 sync "dist" "s3://limn" --acl "bucket-owner-full-control" --cache-control no-store
            - aws cloudfront create-invalidation --distribution-id E3N4FBKGTAIV8D --paths "/index.html"
            - cache delete website-build
